server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: [beans, health, conditions, env, configprops, sessions, metrics, logfile, heapdump, loggers, shutdown]
  endpoint:
    shutdown:
      enabled: true

spring:
  datasource:
    platform: postgres
    username: ${P2_DB_ROLE}
    password: ${P2_DB_PASS}
    url: ${P2_DB_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect